export const storyArray = [
  "You wake up. You are lying on a bed of leaves. As you sit up you notice you are in a forest. Trees surround you in all directions and there are no apparent paths. How did you get here? How do you get out? You hear a grumble come from your belly and so you decide you need to find food first. You look down and see what looks to be a pink berry.",
  "The berry is strangely bitter but you no longer feel hungry. You look up and see the sun right over head. You have 6 hours until night. It would be good to find shelter before then. You don't know what's in the forest, after all. You find a stick on the ground.",
  "Nice, you got a stick. It does 8 attack damage, whatever that means. Alright back to finding shelter. Guess any direction will do. You see some smoke billowing from the direction of the sun's rise. (0+s)",
  "You head east and come to an encampment. You see green men doing village people things. One of them has a hat. You notice your skin is not green. The one with the hat approaches.",
  "You whack him with your stick. He stumbles to the ground with a grunt. Seems weak. His hat is cool as though.",
  "New hat acquired. It has 3 defense and a special ability. This will be useful later in the story. The other green people seem unfazed that you bonked one of them. One of them seems to be selling armour and other wares. He'll probably know what's going on. You approach him.",
  "*Gooba gubba gib gib, adventurer. That is the way we greet people in this game, and is definitely not going to get old quick. I am Thorgan.* You better cut him off before he gives you useless lore dialog. ^I am looking for shelter and story progression I guess.^ *Well apart from this humble village there is a castle in the north that harbours many a peasant. The king has a lot of cool quests, too.* ^Alright, thanks. I won't whack you.^ *Wait what* Time to go... where to?",
  "You venture north toward the castle. After several hours night falls upon you and along with it come the strange sounds and sights of the dark. You hear chattering amongst the trees. You decide you need to find a place to rest for the night. Conveniently there are two sites in front of you: a pitch black cave with a head on a stick at the entrance, and a 3-star AirBnB hostel called 'Your Mum's'. Clearly only one of these options is safe and appropriate.",
  "You begin to make your way into the cave but you are halted by the head on a stick. *Password!* he demands. ^Gizzus a hint!^ you ask. *How did I die?* Well he is a head on a stick... so probably decapitation right? Upon further inspection you notice he has an earring on his right ear, and he is speaking with a lisp. (RIP Freddie)",
  "^Unholy Penetration!^ *Ok you may enter* The floor of the cave is sticky as you creep into the darkness. Suddenly your hat begins glowing purple. The dim purple light is reflected by a shimmer along the cave walls. When viewed from a certain angle, the shimmering dew reveals shapes... or are they letters? Maybe this is like the Mines of Moria entrance and you have to say something to open a door or something. You make out /Beware ~~~~~~ the merchant/",
  "Upon speaking his name two flat panels that once seemed to be stone smoothly spread open revealing to you a range of weapons within. You should take one. You can choose from an axe, a bow and arrow, a hunting knife, and a glock.",
  "You pick up the glock. It does 22 attack damage. Now you're safe to have a snooze. ...You wake up to a light breeze wafting the scent of pig into your den. You wander outside and follow the smell to a seemingly abandoned camp. There is some succulent roast pork on a spit. Suddenly, the meat that had been glistening in the morning light is now overcast in shadow. Something is behind you.",
  "A knight, completely covered in armour faces you down. He is holding a generic sword and looks like he plays basketball. He raises his arm menacingly. (ask questions later)",
  "You shoot at him. You were totally justified. He starts running and you shoot him in the back. Still justified. He turns around and pleads with you *Please stop, I have children!* You shoot him again anyway. The metal-cased man crumples to the ground in a heap. It would be pretty disrespectful to take things from his corpse. (rhymes with previous)",
  "You crack open his damaged armour and search his bloody body. You find a map and his wallet. It contains a picture of his family, he had a wife and 3 kids. The map shows landmarks like the cave, orc village, even the knight's temporary camp. You use it to guide you to the castle's south gate. A guard manning the gate confronts you from behind battlement. *Oi! No outsiders allowed into the castle.* You are going to have to use a speech skill to get past this guy. Perhaps the specialty of the womenfolk will do.",
];

export const answerArray = [
  "eat",
  "pick up",
  "east",
  "attack",
  "take hat",
  "talk",
  "north",
  "cave",
  "AIDS",
  "Thorgan",
  "glock",
  "turn around",
  "shoot",
  "loot",
  "lie",
];
